language: node_js
node_js:
  - "lts/*"

branches:
  only:
  - master

install:
- npm install

script:
- npm run build

deploy:
  local_dir: _dist/
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  fqdn: ota.frantisheq.ml
  on:
    branch: master
